version: '2.1'
services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gnuhealth
      POSTGRES_PASSWORD: gnuhealth
    volumes:
      - ./data/db:/var/lib/postgresql/data

  gnuhealth:
    build:
      context: ./gnuhealth
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_USER: gnuhealth
      DB_PASSWORD: gnuhealth
      DB_HOSTNAME: db
      DB_PORT: 5432
      PYTHONOPTIMIZE: 1
    depends_on:
      - db
    volumes:
      - ./data/attach:/var/lib/trytond/db

  nginx:
    restart: unless-stopped
    image: nginx:1
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - gnuhealth
      - db
    volumes:
      - ./config:/etc/nginx/conf.d
      # http://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot