version: '2.1'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: gnuhealth
      POSTGRES_PASSWORD: gnuhealth
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gnuhealth"]
      interval: 10s
      timeout: 5s
      retries: 5

  gnuhealth:
    build:
      context: ./gnuhealth
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/attach:/gnuhealth/attach
      - ./data/log:/gnuhealth/log

  nginx:
    image: nginx:1-alpine
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - gnuhealth
      - db
    volumes:
      - ./config:/etc/nginx/conf.d
      # http://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
