#!/bin/bash

set -e

export INIT_FILE=/gnuhealth/log/INIT-DO-NOT-DELETE

if [ ! -f "$INIT_FILE" ]; then
    touch ${INIT_FILE}
    su - gnuhealth -c "/bin/bash /gnuhealth/init_db.sh" | tee -a "${INIT_FILE}"
fi
